[project]
name = "hoernchen"
version = "0.6.1"
description = ""
authors = [{name = "Simon Haendeler", email="opensource@haend.de"}]
readme = "README.md"
requires-python = ">=3.7"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"
